import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Kanit } from 'next/font/google'
import Navbar from './components/Navbar'

const inter = Inter({ subsets: ['latin'] })
const kanit = Kanit({subsets:['latin'],weight:'400'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${kanit.className}`}>
    
        {children}
        </body>
    </html>
  )
}
